/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 computer.gltf 
Author: inesmerino (https://sketchfab.com/inesmerino)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/computer-ac4fc7339cd643aa93a0ea0c5b12544c
Title: Computer
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/computer.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.018}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[-282.878, -66.332, -142.962]} rotation={[-Math.PI / 2, 0, 0.878]} scale={100}>
            <mesh geometry={nodes.keyboard_1_Material001_0.geometry} material={materials['Material.001']} />
            <mesh geometry={nodes.keyboard_1_Material006_0.geometry} material={materials['Material.006']} />
            <mesh geometry={nodes.keyboard_1_Material007_0.geometry} material={materials['Material.007']} />
            <mesh geometry={nodes.keyboard_1_Material002_0.geometry} material={materials['Material.002']} />
            <mesh geometry={nodes.keyboard_1_Material004_0.geometry} material={materials['Material.004']} />
          </group>
          <group position={[-217.089, 316.787, -225.179]} rotation={[-Math.PI / 2, 0, 0.878]} scale={100}>
            <mesh geometry={nodes.monitor_1_Material001_0.geometry} material={materials['Material.001']} />
            <mesh geometry={nodes.monitor_1_Material006_0.geometry} material={materials['Material.006']} />
            <mesh geometry={nodes.monitor_1_Material007_0.geometry} material={materials['Material.007']} />
            <mesh geometry={nodes.monitor_1_Material009_0.geometry} material={materials['Material.009']} />
            <mesh geometry={nodes.monitor_1_Material002_0.geometry} material={materials['Material.002']} />
            <mesh geometry={nodes.monitor_1_Material004_0.geometry} material={materials['Material.004']} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/computer.gltf')
