/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 computer.gltf 
Author: UROD Engine (https://sketchfab.com/Starven38)
License: CC-BY-SA-4.0 (http://creativecommons.org/licenses/by-sa/4.0/)
Source: https://sketchfab.com/3d-models/personal-computer-aa398650fe6e4baa8771c71266d842f4
Title: Personal Computer
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/computer.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.003}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Cube_PC_0.geometry} material={materials.material} />
            <mesh geometry={nodes.Cube_LightMat_0.geometry} material={materials.LightMat} />
            <mesh geometry={nodes.Cube_Screen_0.geometry} material={materials.Screen} />
            <mesh geometry={nodes.Cube_Keyboard_0.geometry} material={materials.Keyboard} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/computer.gltf')
